name: Spellcheck
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
jobs:
  Spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node.js 20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: yarn
      - name: Run Spellcheck
        run: yarn spellcheck
